### ISSUE TITLE
Release for pdfbox 2.0.8?

### ISSUE THREAD

**Issue by rigolepe** [overview/pdfocr#5]
Is there a roadmap for pdfbox 2.0.8 support? 

cheers,
   Peter

**Comment by adamhooper** [comment]
Thanks for the request. I've pushed a v0.0.6 to Maven which uses pdfbox 2.0.8. (I updated _all_ dependencies, actually.)

As always with pdfbox changes: be wary. There are often surprises, even between patch releases. For instance: this release uses a new crypto-related dependency, `org.bouncycastle/bcpkix-jdk15on`.

**Comment by rigolepe** [comment]
Thanks!
